name: test-and-build

on:
  - push
  - pull_request

jobs:
  test-go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - name: Test
        run: go test ./...
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
      - name: Build
        run: make